# Generated by Django 3.0.8 on 2021-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='pictures')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('dsm', models.BooleanField(default=False)),
            ],
        ),
    ]
