# Generated by Django 3.0.8 on 2021-01-14 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210114_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcompany',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
