# Generated by Django 3.0.8 on 2021-01-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_destinationcompany_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationcompany',
            name='slug',
        ),
        migrations.AlterField(
            model_name='destinationcompany',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
