# Generated by Django 3.0.8 on 2021-01-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210115_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcompany',
            name='d_sm',
            field=models.BooleanField(default=False),
        ),
    ]
